
version: "3"
services:
  app:
    image: nvynnyk/python-projectnzrb:2.0
    build: 
      context:
        ./app
    privileged: true 
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock   
    links:
      - db
    ports:
      - "5000:5000"
    networks:
      - appnet  
    
    depends_on:
      - db


  db:
    image: mysql:8.0.25
    privileged: true
    ports:
      - "30000:3306"
    networks:
      - appnet
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock   
      - ./db-master:/docker-entrypoint-initdb.d/:ro
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]

volumes:
   db-master:

networks:
  appnet:

